monolog:
    channels: ['crawler', 'audit', 'proxy', 'alexa', 'messenger']
    handlers:
        errors:
            type: fingers_crossed
            handler: errors_file
            action_level: error
            channels: ['!alexa', '!crawler', '!proxy', '!audit']
        errors_file:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            formatter: Monolog\Formatter\JsonFormatter
            channels: ['!alexa', '!crawler', '!proxy', '!audit']
        alexa_error:
            type: fingers_crossed
            handler: alexa_error_file
            action_level: error
            channels: ['alexa', 'crawler']
        alexa_error_file:
            type: rotating_file
            path: "%kernel.logs_dir%/alexa/%kernel.environment%_error.log"
            level: error
            formatter: Monolog\Formatter\JsonFormatter
